Repository jasp-stats/jasp-desktop, pull requests merged in 2022-01, with the labels that each got.

#4611 Fixing the Slider.qml
  Desktop/components/JASP/Controls/Slider.qml
Labels: Bug: Medium, Layer: UI/UX

#4679 Add the possibility to set different default values in a TableView according to their column and row.
  Desktop/components/JASP/Controls/DoubleField.qml
  Desktop/components/JASP/Controls/FormulaField.qml
  Desktop/components/JASP/Controls/IntegerField.qml
  Desktop/components/JASP/Controls/TableView.qml
  Desktop/components/JASP/Controls/TextField.qml
  Desktop/components/JASP/Widgets/BasicThreeButtonTableView.qml
  Desktop/widgets/boundcontroltableview.cpp
  Desktop/widgets/boundcontroltableview.h
  Desktop/widgets/listmodeltableviewbase.cpp
  Desktop/widgets/tableviewbase.cpp
  Desktop/widgets/tableviewbase.h
  Desktop/widgets/textinputbase.cpp
  Desktop/widgets/textinputbase.h
Labels: Layer: Qt/QML

#4696 Qt Acknowledgement
  NOTICE.txt
Labels: Layer: Qt/QML

#4687 Fixes all modules are "dynamic"
  Desktop/analysis/analysis.cpp
  Desktop/analysis/analysis.h
Labels: Layer: Core

#4693 Removing calls to `convertPagePathToLower`
  Desktop/utilities/helpmodel.cpp
Labels: OS: Linux / Flatpak, Difficulty: Easy, Layer: Qt/QML
